package com.aiforjava.message;

/**
 * Defines the roles of different participants in a chat conversation.
 * These roles are typically used to categorize messages sent to and received from
 * Large Language Models (LLMs), influencing how the model interprets and responds
 * to the conversation.
 */
public enum MessageRole {
    /**
     * Represents a system message, often used to set the initial behavior or context
     * for the AI assistant. For example, "You are a helpful assistant."
     */
    SYSTEM,
    /**
     * Represents a message from the end-user.
     */
    USER,
    /**
     * Represents a message generated by the AI assistant.
     */
    ASSISTANT,
    /**
     * Represents a message related to function calls, typically used in advanced
     * LLM interactions where the model can invoke external tools or functions.
     */
    FUNCTIONS
}


